// react/src/domain/board/ListPage.tsx
import { useState, useEffect, type ChangeEvent, type SubmitEvent } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { fetchTaskList, type TaskItem, type TaskFilterParams } from './api';

export default function BoardListPage() {
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();

  // 1. 입력 폼의 상태 (Client State)
  const [filter, setFilter] = useState<TaskFilterParams>({
    keyword: searchParams.get('keyword') || '',
    status: searchParams.get('status') || '',
    start_date: searchParams.get('start_date') || '',
    end_date: searchParams.get('end_date') || '',
  });

  // 2. 실제 API 조회에 적용되는 쿼리 상태 (URL searchParams 기반)
  const activeFilter: TaskFilterParams = {
    keyword: searchParams.get('keyword') || '',
    status: searchParams.get('status') || '',
    start_date: searchParams.get('start_date') || '',
    end_date: searchParams.get('end_date') || '',
  };

  // URL 파라미터가 외부(뒤로가기/링크)에서 변경될 경우 입력 폼 상태(filter) 동기화
  useEffect(() => {
    setFilter({
      keyword: searchParams.get('keyword') || '',
      status: searchParams.get('status') || '',
      start_date: searchParams.get('start_date') || '',
      end_date: searchParams.get('end_date') || '',
    });
  }, [searchParams]);

  // 3. React Query를 통한 서버 데이터 조회 (Server State)
  const {
    data: items = [],
    isLoading,
    isError,
    error,
  } = useQuery<TaskItem[], Error>({
    queryKey: ['tasks', activeFilter], // activeFilter가 바뀔 때만 자동 재조회 & 캐싱
    queryFn: () => fetchTaskList(activeFilter),
  });

  // 뱃지 / 프로그레스바 클래스 헬퍼
  const getBadgeClass = (status: string): string => {
    switch (status) {
      case 'RUNNING':
      case 'PROGRESS':
        return 'text-bg-primary';
      case 'DONE':
      case 'COMPLETED':
        return 'text-bg-success';
      case 'READY':
      case 'PENDING':
        return 'text-bg-warning';
      case 'FAILED':
        return 'text-bg-danger';
      default:
        return 'text-bg-secondary';
    }
  };

  const getProgressClass = (status: string): string => {
    switch (status) {
      case 'DONE':
      case 'COMPLETED':
        return 'bg-success';
      case 'READY':
      case 'PENDING':
        return 'bg-warning';
      case 'FAILED':
        return 'bg-danger';
      default:
        return '';
    }
  };

  // 4. 이벤트 핸들러
  const handleInputChange = (
    e: ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    const { id, value } = e.target;
    setFilter((prev) => ({ ...prev, [id]: value }));
  };

  // 검색 시 URL의 SearchParams를 업데이트 (자동으로 React Query가 감지하여 fetch)
  const handleSubmit = (e: SubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    const params = new URLSearchParams();
    Object.entries(filter).forEach(([key, val]) => {
      if (val) params.set(key, String(val));
    });
    setSearchParams(params);
  };

  // 초기화 시 폼 상태와 URL 파라미터를 모두 비움
  const handleReset = () => {
    const emptyFilter: TaskFilterParams = {
      keyword: '',
      status: '',
      start_date: '',
      end_date: '',
    };
    setFilter(emptyFilter);
    setSearchParams({});
  };

  // 상세 페이지 이동 (현재 검색 조건 유지)
  const handleRowClick = (item: TaskItem) => {
    const id = item.id || item.task_id || '';
    const params = new URLSearchParams();
    Object.entries(activeFilter).forEach(([key, value]) => {
      if (value) params.append(key, String(value));
    });

    navigate(`/board/${id}?${params.toString()}`);
  };

  return (
    <div className="board-list-page">
      <div className="page-title mb-4">
        <h1>작업 목록</h1>
        <p className="text-muted">
          키워드, 상태, 기간 조건으로 작업 진행 현황을 검색합니다.
        </p>
      </div>

      {/* 검색 필터 폼 */}
      <section className="panel p-4 mb-4 border rounded bg-white">
        <form className="row g-3" onSubmit={handleSubmit}>
          <div className="col-md-4">
            <label className="form-label" htmlFor="keyword">
              검색어
            </label>
            <input
              id="keyword"
              className="form-control"
              type="text"
              placeholder="검색어 입력"
              value={filter.keyword || ''}
              onChange={handleInputChange}
            />
          </div>

          <div className="col-md-2">
            <label className="form-label" htmlFor="status">
              상태
            </label>
            <select
              id="status"
              className="form-select"
              value={filter.status || ''}
              onChange={handleInputChange}
            >
              <option value="">전체</option>
              <option value="PENDING">PENDING</option>
              <option value="PROGRESS">PROGRESS</option>
              <option value="COMPLETED">COMPLETED</option>
              <option value="FAILED">FAILED</option>
            </select>
          </div>

          <div className="col-md-3">
            <label className="form-label" htmlFor="start_date">
              시작일
            </label>
            <input
              id="start_date"
              className="form-control"
              type="date"
              value={filter.start_date || ''}
              onChange={handleInputChange}
            />
          </div>

          <div className="col-md-3">
            <label className="form-label" htmlFor="end_date">
              종료일
            </label>
            <input
              id="end_date"
              className="form-control"
              type="date"
              value={filter.end_date || ''}
              onChange={handleInputChange}
            />
          </div>

          <div className="col-12 d-flex justify-content-end gap-2">
            <button
              className="btn btn-outline-secondary"
              type="button"
              onClick={handleReset}
            >
              초기화
            </button>
            <button className="btn btn-primary" type="submit">
              검색
            </button>
          </div>
        </form>
      </section>

      {/* 테이블 목록 */}
      <section className="panel border rounded bg-white">
        <div className="table-responsive">
          <table className="table table-hover align-middle mb-0">
            <thead className="table-light">
              <tr>
                <th scope="col">No</th>
                <th scope="col">작업 ID</th>
                <th scope="col">유형</th>
                <th scope="col">데이터 키</th>
                <th scope="col">상태</th>
                <th scope="col">진행률</th>
                <th scope="col">수정 일시</th>
              </tr>
            </thead>
            <tbody>
              {isLoading ? (
                <tr>
                  <td colSpan={7} className="text-center py-4">
                    데이터를 로딩 중입니다...
                  </td>
                </tr>
              ) : isError ? (
                <tr>
                  <td colSpan={7} className="text-center text-danger py-4">
                    {error?.message ||
                      '데이터를 불러오는 중 오류가 발생했습니다.'}
                  </td>
                </tr>
              ) : items.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center py-4">
                    검색 결과가 없습니다.
                  </td>
                </tr>
              ) : (
                items.map((t: TaskItem, idx: number) => {
                  const status = t.status || '';
                  const progress = Number.isFinite(t.progress)
                    ? (t.progress as number)
                    : t.progress ?? 0;
                  const updated = t.updated_at || t.created_at || '';
                  const dataKey = t.data_key || '';

                  return (
                    <tr
                      key={t.id || t.task_id || idx}
                      role="button"
                      onClick={() => handleRowClick(t)}
                    >
                      <td>{idx + 1}</td>
                      <td className="fw-semibold">{t.task_id || ''}</td>
                      <td>{t.task_type || ''}</td>
                      <td>{dataKey}</td>
                      <td>
                        <span className={`badge ${getBadgeClass(status)}`}>
                          {status}
                        </span>
                      </td>
                      <td>
                        <div className="progress" style={{ height: '8px' }}>
                          <div
                            className={`progress-bar ${getProgressClass(
                              status
                            )}`}
                            style={{ width: `${progress}%` }}
                          ></div>
                        </div>
                      </td>
                      <td>{updated}</td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

// vue/src/features/board/ListPage.vue
<!-- vue\src\features\board\ListPage.vue -->
<template>
  <div class="board-list-page">
    <div class="page-title mb-4">
      <h1>작업 목록</h1>
      <p class="text-muted">키워드, 상태, 기간 조건으로 작업 진행 현황을 검색합니다.</p>
    </div>

    <!-- 검색 폼 영역 -->
    <section class="panel p-4 mb-4 border rounded bg-white">
      <form class="row g-3" @submit.prevent="fetchList" @reset="handleReset">
        <div class="col-md-4">
          <label class="form-label" for="keyword">검색어</label>
          <input
            id="keyword"
            v-model="searchForm.keyword"
            class="form-control"
            type="text"
            placeholder="검색어 입력"
          />
        </div>
        <div class="col-md-2">
          <label class="form-label" for="status">상태</label>
          <select id="status" v-model="searchForm.status" class="form-select">
            <option value="">전체</option>
            <option value="PENDING">PENDING</option>
            <option value="PROGRESS">PROGRESS</option>

            <option value="COMPLETED">COMPLETED</option>
            <option value="FAILED">FAILED</option>
          </select>
        </div>
        <div class="col-md-3">
          <label class="form-label" for="start_date">시작일</label>
          <input id="start_date" v-model="searchForm.start_date" class="form-control" type="date" />
        </div>
        <div class="col-md-3">
          <label class="form-label" for="end_date">종료일</label>
          <input id="end_date" v-model="searchForm.end_date" class="form-control" type="date" />
        </div>
        <div class="col-12 d-flex justify-content-end gap-2">
          <button class="btn btn-outline-secondary" type="reset">초기화</button>
          <button class="btn btn-primary" type="submit">검색</button>
        </div>
      </form>
    </section>

    <!-- 테이블 데이터 영역 -->
    <section class="panel border rounded bg-white">
      <div class="table-responsive">
        <table class="table table-hover align-middle mb-0">
          <thead class="table-light">
            <tr>
              <th scope="col">No</th>
              <th scope="col">작업 ID</th>
              <th scope="col">유형</th>
              <th scope="col">데이터 키</th>
              <th scope="col">상태</th>
              <th scope="col">진행률</th>
              <th scope="col">수정 일시</th>
            </tr>
          </thead>
          <tbody>
            <!-- 에러 발생 시 -->
            <tr v-if="errorMessage">
              <td colspan="7" class="text-center text-danger py-4">{{ errorMessage }}</td>
            </tr>

            <!-- 데이터가 없을 때 -->
            <tr v-else-if="items.length === 0">
              <td colspan="7" class="text-center py-4">검색 결과가 없습니다.</td>
            </tr>

            <!-- 데이터가 있을 때 반복 출력 -->
            <tr
              v-else
              v-for="(t, idx) in items"
              :key="t.id || t.ID || idx"
              role="button"
              @click="goDetail(t)"
            >
              <td>{{ idx + 1 }}</td>
              <td class="fw-semibold">{{ t.task_id || '' }}</td>
              <td>{{ t.task_type || '' }}</td>
              <td>{{ t.data_key || '' }}</td>
              <td>
                <span :class="['badge', badgeClass(t.status)]">{{ t.status || '' }}</span>
              </td>
              <td>
                <div class="progress" style="height: 8px;">
                  <div
                    :class="['progress-bar', progressClass(t.status)]"
                    :style="{ width: getProgress(t.progress) + '%' }"
                  ></div>
                </div>
              </td>
              <td>{{ t.updated_at || t.created_at || '' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue';
import { useRouter, useRoute } from 'vue-router';

const router = useRouter();
const route = useRoute();

// API 기본 URL (.env 파일 참조)
const viteApiUrl = `${import.meta.env.VITE_API_URL || ''}/api/v1/tasks`;

// 검색 폼 반응형 상태
const searchForm = reactive({
  keyword: '',
  status: '',
  start_date: '',
  end_date: ''
});

// 목록 데이터 및 에러 상태
const items = ref([]);
const errorMessage = ref('');

// 진행률 수치 계산 헬퍼
const getProgress = (progress) => {
  if (Number.isFinite(progress)) return progress;
  return progress ?? 0;
};

// 뱃지 CSS 클래스 매핑
const badgeClass = (status) => {
  if (!status) return 'text-bg-secondary';
  if (status === 'RUNNING' || status === 'PROGRESS') return 'text-bg-primary';
  if (status === 'DONE' || status === 'COMPLETED') return 'text-bg-success';
  if (status === 'READY' || status === 'PENDING') return 'text-bg-warning';
  if (status === 'FAILED') return 'text-bg-danger';
  return 'text-bg-secondary';
};

// 프로그레스 바 CSS 클래스 매핑
const progressClass = (status) => {
  if (status === 'DONE' || status === 'COMPLETED') return 'bg-success';
  if (status === 'READY' || status === 'PENDING') return 'bg-warning';
  if (status === 'FAILED') return 'bg-danger';
  return '';
};

// 목록 조회 함수
const fetchList = async () => {
  errorMessage.value = '';

  // 비어있지 않은 파라미터만 추출
  const params = new URLSearchParams();
  Object.keys(searchForm).forEach((key) => {
    if (searchForm[key]) {
      params.append(key, searchForm[key]);
    }
  });

  const url = `${viteApiUrl}?${params.toString()}`;

  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const resp = await res.json();

    const payload = resp && typeof resp === 'object' && 'data' in resp ? resp.data : resp;
    const fetchedItems = payload.items || payload;

    items.value = Array.isArray(fetchedItems) ? fetchedItems : [];
  } catch (err) {
    console.error('fetchList error', err);
    errorMessage.value = '데이터를 불러오는 중 오류가 발생했습니다.';
  }
};

// 폼 초기화
const handleReset = () => {
  searchForm.keyword = '';
  searchForm.status = '';
  searchForm.start_date = '';
  searchForm.end_date = '';
  setTimeout(fetchList, 0);
};

// 상세 페이지 이동 (Vue Router 처리)
const goDetail = (item) => {
  const id = item.id ?? item.ID ?? '';
  
  // 현재 검색 조건 쿼리 스트링 유지
  const query = {};
  Object.keys(searchForm).forEach((key) => {
    if (searchForm[key]) query[key] = searchForm[key];
  });

  router.push({
    path: `/board/${id}`,
    query: { id, ...query }
  });
};

// 컴포넌트 마운트 시 (초기 로드) URL Query 파라미터 바인딩 및 데이터 요청
onMounted(() => {
  if (route.query) {
    if (route.query.keyword) searchForm.keyword = route.query.keyword;
    if (route.query.status) searchForm.status = route.query.status;
    if (route.query.start_date) searchForm.start_date = route.query.start_date;
    if (route.query.end_date) searchForm.end_date = route.query.end_date;
  }
  fetchList();
});
</script>

<style scoped>
/* 행 클릭 시 마우스 커서 손모양 변경 */
tr[role='button'] {
  cursor: pointer;
}
</style>
